/**
 ******************************************************************************
 * @file           : 001ToggleLED.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f407xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(){
	for(uint32_t i = 0; i < 5000000/4; i++);
}

int main(void)
{
	// CASE 1 : TRY TOGGLE WITH ONBOARD LED PD13 USE PUSH PULL
	// CASE 2 : TRY TOGGLE WITH ONBOARD LED PD14 USE OPEN DRAIN
	// INIT A led
	//	GPIO_HAL LD13;
	//	GPIO_HAL LD14;
	//
	//	// Select port mode speed
	//	LD13.pGPIOx = GPIOD;
	//	LD13.GPIO_PIN_CONFIG.GPIO_Pin_mode = GPIO_MODE_OUTPUT;
	//	LD13.GPIO_PIN_CONFIG.GPIO_Pin_num = GPIO_PIN_13;
	//	LD13.GPIO_PIN_CONFIG.GPIO_Pin_speed = GPIO_SPEED_H;
	//	LD13.GPIO_PIN_CONFIG.GPIO_Pin_OUTPUT_TYPE = GPIO_MODE_OUTPUT_PP;
	//	LD13.GPIO_PIN_CONFIG.GPIO_Pin_PuPdCONTROL = GPIO_PUPD_DIS;
	//	// Select port mode speed
	//	LD14.pGPIOx = GPIOD;
	//	LD14.GPIO_PIN_CONFIG.GPIO_Pin_mode = GPIO_MODE_OUTPUT;
	//	LD14.GPIO_PIN_CONFIG.GPIO_Pin_num = GPIO_PIN_14;
	//	LD14.GPIO_PIN_CONFIG.GPIO_Pin_speed = GPIO_SPEED_H;
	//	LD14.GPIO_PIN_CONFIG.GPIO_Pin_OUTPUT_TYPE = GPIO_MODE_OUTPUT_OD;
	//	LD14.GPIO_PIN_CONFIG.GPIO_Pin_PuPdCONTROL = GPIO_PUPD_PU;
	//	// CLK already ENABLE WHEN CALL GPIO_Init
	//	GPIO_Init(&LD13);
	//	GPIO_Init(&LD14);
	//	GPIO_Write_Pin(GPIOD, GPIO_PIN_13, SET);
	//	GPIO_Write_Pin(GPIOD, GPIO_PIN_14, SET);
	/* Loop forever */
	//	while(1){
	//		GPIO_Toggle_Output(GPIOD, GPIO_PIN_13);
	//		GPIO_Toggle_Output(GPIOD, GPIO_PIN_14);
	//		delay();
	//	}

	//==============================================================================================================================
	//CASE 3: USE BUTTON (1 INPUT 1 OUTPUT)
//	GPIO_HAL BUTTONA; // PA0 : ONBOARD BUTTON
//	GPIO_HAL LD13;

	// Select port mode speed
//	LD13.pGPIOx = GPIOD;
//	LD13.GPIO_PIN_CONFIG.GPIO_Pin_mode = GPIO_MODE_OUTPUT;
//	LD13.GPIO_PIN_CONFIG.GPIO_Pin_num = GPIO_PIN_13;
//	LD13.GPIO_PIN_CONFIG.GPIO_Pin_speed = GPIO_SPEED_H;
//	LD13.GPIO_PIN_CONFIG.GPIO_Pin_OUTPUT_TYPE = GPIO_MODE_OUTPUT_PP;
//	LD13.GPIO_PIN_CONFIG.GPIO_Pin_PuPdCONTROL = GPIO_PUPD_DIS;
//	// Select port mode speed
//	BUTTONA.pGPIOx = GPIOA;
//	BUTTONA.GPIO_PIN_CONFIG.GPIO_Pin_mode = GPIO_MODE_INPUT;
//	BUTTONA.GPIO_PIN_CONFIG.GPIO_Pin_num = GPIO_PIN_0;
//	BUTTONA.GPIO_PIN_CONFIG.GPIO_Pin_speed = GPIO_SPEED_H;
//	//LD14.GPIO_PIN_CONFIG.GPIO_Pin_OUTPUT_TYPE = GPIO_MODE_OUTPUT_OD;
//	BUTTONA.GPIO_PIN_CONFIG.GPIO_Pin_PuPdCONTROL = GPIO_PUPD_DIS;
//	// CLK already ENABLE WHEN CALL GPIO_Init
//	GPIO_Init(&LD13);
//	GPIO_Init(&BUTTONA);
//
//	GPIO_Write_Pin(GPIOD, GPIO_PIN_13, SET);
//	while(1){
//		delay();
//		if(GPIO_Read_Pin(GPIOA, GPIO_PIN_0)) // pressed is 1
//			GPIO_Toggle_Output(GPIOD, GPIO_PIN_13);
//
//	}

	//==============================================================================================================================
	//CASE 4: USE BUTTON (1 INPUT 1 OUTPUT) connect button and led outside
	GPIO_HAL GPIOBtn; // PA10 : ONBOARD BUTTON
	GPIO_HAL LB8;

	LB8.pGPIOx = GPIOB;
	LB8.GPIO_PIN_CONFIG.GPIO_Pin_mode = GPIO_MODE_OUTPUT;
	LB8.GPIO_PIN_CONFIG.GPIO_Pin_num = GPIO_PIN_13;
	LB8.GPIO_PIN_CONFIG.GPIO_Pin_speed = GPIO_SPEED_H;
	LB8.GPIO_PIN_CONFIG.GPIO_Pin_OUTPUT_TYPE = GPIO_MODE_OUTPUT_PP;
	LB8.GPIO_PIN_CONFIG.GPIO_Pin_PuPdCONTROL = GPIO_PUPD_DIS;
	// Select port mode speed
	GPIOBtn.pGPIOx = GPIOA;
	GPIOBtn.GPIO_PIN_CONFIG.GPIO_Pin_mode = GPIO_MODE_INPUT;
	GPIOBtn.GPIO_PIN_CONFIG.GPIO_Pin_num = GPIO_PIN_0;
	GPIOBtn.GPIO_PIN_CONFIG.GPIO_Pin_speed = GPIO_SPEED_H;
	//LD14.GPIO_PIN_CONFIG.GPIO_Pin_OUTPUT_TYPE = GPIO_MODE_OUTPUT_OD;
	GPIOBtn.GPIO_PIN_CONFIG.GPIO_Pin_PuPdCONTROL = GPIO_PUPD_DIS;
	// CLK already ENABLE WHEN CALL GPIO_Init
	GPIO_Init(&LB8);
	GPIO_Init(&GPIOBtn);

	GPIO_Write_Pin(GPIOB, GPIO_PIN_8, SET);
	while(1){
		delay();
		if(GPIO_Read_Pin(GPIOA, GPIO_PIN_10)) // pressed is 1
			GPIO_Toggle_Output(GPIOB, GPIO_PIN_8);

	}








	return 0;
}
